/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const ContactForm = IDL.Record({
  'name' : IDL.Text,
  'email' : IDL.Text,
  'message' : IDL.Text,
  'phone' : IDL.Text,
});
export const LoanInquiry = IDL.Record({
  'name' : IDL.Text,
  'phone' : IDL.Text,
  'amount' : IDL.Nat,
});

export const idlService = IDL.Service({
  'getAllContactForms' : IDL.Func([], [IDL.Vec(ContactForm)], ['query']),
  'getAllLoanInquiries' : IDL.Func([], [IDL.Vec(LoanInquiry)], ['query']),
  'getContactForm' : IDL.Func([IDL.Nat], [ContactForm], ['query']),
  'getLoanInquiry' : IDL.Func([IDL.Nat], [LoanInquiry], ['query']),
  'submitContactForm' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [IDL.Nat],
      [],
    ),
  'submitLoanInquiry' : IDL.Func([IDL.Text, IDL.Text, IDL.Nat], [IDL.Nat], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const ContactForm = IDL.Record({
    'name' : IDL.Text,
    'email' : IDL.Text,
    'message' : IDL.Text,
    'phone' : IDL.Text,
  });
  const LoanInquiry = IDL.Record({
    'name' : IDL.Text,
    'phone' : IDL.Text,
    'amount' : IDL.Nat,
  });
  
  return IDL.Service({
    'getAllContactForms' : IDL.Func([], [IDL.Vec(ContactForm)], ['query']),
    'getAllLoanInquiries' : IDL.Func([], [IDL.Vec(LoanInquiry)], ['query']),
    'getContactForm' : IDL.Func([IDL.Nat], [ContactForm], ['query']),
    'getLoanInquiry' : IDL.Func([IDL.Nat], [LoanInquiry], ['query']),
    'submitContactForm' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [IDL.Nat],
        [],
      ),
    'submitLoanInquiry' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Nat],
        [IDL.Nat],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };